import { useEffect, useState } from 'react';
import { reportCardsApi } from '../../services/reportCards';
export function ReportCardsPage() {
  const [cards, setCards] = useState<any[]>([]); const [resultId, setResultId] = useState(''); const [gradeId, setGradeId] = useState(''); const [institution, setInstitution] = useState('College ERP'); const [error, setError] = useState<string | null>(null);
  const load = async () => { const data = await reportCardsApi.list(''); setCards(data.items ?? []); };
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  const generate = async () => { setError(null); await reportCardsApi.generate({ result_id: resultId, grade_calculation_id: gradeId || undefined, institution_name: institution, branding: { tagline: 'Detailed Marks Certificate' } }); await load(); };
  return <section style={{ border: '1px solid #d7dce2', borderRadius: 12, padding: '1rem', marginBlock: '1rem' }}><h2>Report Cards (DMC)</h2><p>Generate printable Detailed Marks Certificates with subject marks, percentage, GPA/CGPA where available, and QR verification.</p><div style={{ display: 'flex', gap: '.75rem', flexWrap: 'wrap' }}><input aria-label="Institution" value={institution} onChange={(e) => setInstitution(e.target.value)} /><input aria-label="Result ID" placeholder="Result ID" value={resultId} onChange={(e) => setResultId(e.target.value)} /><input aria-label="Grade calculation ID" placeholder="Grade calculation ID (optional)" value={gradeId} onChange={(e) => setGradeId(e.target.value)} /><button disabled={!resultId || !institution} onClick={generate}>Generate DMC</button></div>{error && <p role="alert" style={{ color: '#b42318' }}>{error}</p>}<div style={{ overflowX: 'auto', marginTop: '1rem' }}><table><thead><tr><th>Student</th><th>Status</th><th>Verification</th><th>Actions</th></tr></thead><tbody>{cards.map((c) => <tr key={c.id}><td>{c.student_id}</td><td>{c.status}</td><td>{c.verification_code}</td><td><button onClick={() => { const w = window.open('', '_blank'); if (w) { w.document.write(c.printable_html); w.document.close(); } }}>Print</button><button disabled={c.status === 'issued'} onClick={async () => { await reportCardsApi.issue(c.id); await load(); }}>Issue</button></td></tr>)}</tbody></table></div></section>;
}
