export interface PortalStudentProfile { id:string; first_name:string; last_name:string; admission_number:string; program:string; current_class:string; current_section?:string; academic_session:string; status:string; }
export interface PortalAttendanceSummary { total:number; present:number; absent:number; late:number; excused:number; percentage:number; }
export interface StudentPortalDashboard { profile:PortalStudentProfile; attendance:PortalAttendanceSummary; timetable:Array<{weekday:number; teacher_name:string; entry_type:string}>; results:Array<{exam_id:string; percentage:string; outcome:string}>; merit_positions:Array<{rank:number; percentage:string}>; challans:Array<{challan_number:string; status:string; balance_amount:string}>; payments:Array<{reference_number:string; amount:string; status:string}>; calendar:Array<{title:string; start_date:string; end_date:string}>; notifications:Array<{title:string; message:string}>; downloads:Array<{title:string; type:string}>; }
export interface ParentPortalDashboard { children: StudentPortalDashboard[]; teacher_communication:Array<Record<string,string>>; }
export interface TeacherPortalDashboard { teacher_id:string; timetable:Array<{weekday:number; section_id:string; subject_id:string; entry_type:string}>; attendance_sessions:Array<{id:string; section_id:string; attendance_date:string; status:string}>; marks_entry:Array<Record<string,string>>; result_review:Array<Record<string,string>>; student_performance:Array<Record<string,string>>; announcements:Array<Record<string,string>>; class_management:Array<Record<string,string>>; }
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? '/api/v1';
async function getJson<T>(path:string, role:string): Promise<T> { const r=await fetch(`${API_BASE_URL}${path}`, { headers: { 'X-Role': role } }); if(!r.ok) throw new Error(`Unable to load ${path}`); return r.json(); }
export const getStudentPortal = (studentId:string) => getJson<StudentPortalDashboard>(`/portal/student/students/${studentId}/dashboard`, 'administrator');
export const getParentPortal = () => getJson<ParentPortalDashboard>('/portal/parent/dashboard', 'administrator');
export const getTeacherPortal = () => getJson<TeacherPortalDashboard>('/portal/teacher/dashboard', 'administrator');
