-- Examination Management schema migration for PostgreSQL.
CREATE TABLE IF NOT EXISTS exam_types (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, code varchar(40) NOT NULL, name varchar(120) NOT NULL, description text, default_weightage numeric(5,2) NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_exam_type_code_per_college UNIQUE (college_id, code));
CREATE TABLE IF NOT EXISTS exams (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, exam_type_id varchar(36) NOT NULL REFERENCES exam_types(id) ON DELETE RESTRICT, session_id varchar(36) NOT NULL REFERENCES academic_sessions(id) ON DELETE RESTRICT, program_id varchar(36) REFERENCES programs(id) ON DELETE RESTRICT, class_id varchar(36) NOT NULL REFERENCES academic_classes(id) ON DELETE CASCADE, section_id varchar(36) NOT NULL REFERENCES sections(id) ON DELETE CASCADE, name varchar(180) NOT NULL, start_date date NOT NULL, end_date date NOT NULL, status varchar(20) NOT NULL DEFAULT 'draft', created_by varchar(64) NOT NULL, published_at timestamptz, locked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT uq_exam_name_scope UNIQUE (college_id, session_id, section_id, exam_type_id, name), CONSTRAINT ck_exam_date_range CHECK (start_date <= end_date));
CREATE TABLE IF NOT EXISTS assessment_components (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, exam_id varchar(36) NOT NULL REFERENCES exams(id) ON DELETE CASCADE, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, component_type varchar(20) NOT NULL, name varchar(120) NOT NULL, maximum_marks numeric(7,2) NOT NULL, passing_marks numeric(7,2) NOT NULL, weightage numeric(5,2) NOT NULL, is_internal boolean NOT NULL DEFAULT true, is_practical boolean NOT NULL DEFAULT false, CONSTRAINT uq_assessment_component_exam_subject_type UNIQUE (exam_id, subject_id, component_type), CONSTRAINT ck_component_max_positive CHECK (maximum_marks > 0), CONSTRAINT ck_component_pass_non_negative CHECK (passing_marks >= 0), CONSTRAINT ck_component_pass_lte_max CHECK (passing_marks <= maximum_marks), CONSTRAINT ck_component_weightage_range CHECK (weightage >= 0 AND weightage <= 100));
CREATE TABLE IF NOT EXISTS exam_halls (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, name varchar(160) NOT NULL, code varchar(40) NOT NULL, capacity integer NOT NULL, is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_exam_hall_code_per_college UNIQUE (college_id, code), CONSTRAINT ck_exam_hall_capacity_positive CHECK (capacity > 0));
CREATE TABLE IF NOT EXISTS exam_schedules (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, exam_id varchar(36) NOT NULL REFERENCES exams(id) ON DELETE CASCADE, section_id varchar(36) NOT NULL REFERENCES sections(id) ON DELETE CASCADE, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, hall_id varchar(36) NOT NULL REFERENCES exam_halls(id) ON DELETE RESTRICT, component_type varchar(20) NOT NULL, exam_date date NOT NULL, start_time time NOT NULL, end_time time NOT NULL, instructions text, CONSTRAINT uq_exam_schedule_subject_component UNIQUE (exam_id, subject_id, component_type), CONSTRAINT ck_exam_schedule_time_range CHECK (start_time < end_time));
CREATE TABLE IF NOT EXISTS invigilator_assignments (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, schedule_id varchar(36) NOT NULL REFERENCES exam_schedules(id) ON DELETE CASCADE, teacher_id varchar(64) NOT NULL, teacher_name varchar(160) NOT NULL, exam_date date NOT NULL, start_time time NOT NULL, end_time time NOT NULL, assigned_by varchar(64) NOT NULL, CONSTRAINT uq_invigilator_schedule_teacher UNIQUE (schedule_id, teacher_id));
CREATE INDEX IF NOT EXISTS ix_exam_types_college_active ON exam_types(college_id, is_active);
CREATE INDEX IF NOT EXISTS ix_exams_college_session_status ON exams(college_id, session_id, status);
CREATE INDEX IF NOT EXISTS ix_exams_college_section_dates ON exams(college_id, section_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS ix_components_college_exam_subject ON assessment_components(college_id, exam_id, subject_id);
CREATE INDEX IF NOT EXISTS ix_exam_halls_college_active ON exam_halls(college_id, is_active);
CREATE INDEX IF NOT EXISTS ix_exam_schedules_college_date_hall ON exam_schedules(college_id, exam_date, hall_id, start_time, end_time);
CREATE INDEX IF NOT EXISTS ix_exam_schedules_college_section_date ON exam_schedules(college_id, section_id, exam_date);
CREATE INDEX IF NOT EXISTS ix_invigilators_college_teacher_date ON invigilator_assignments(college_id, teacher_id, exam_date);
