-- Enterprise Finance (Fee Management): fee heads, templates, challans, scholarships, installments, payments, refunds.
CREATE TABLE fee_heads (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(120) NOT NULL, head_type VARCHAR(32) NOT NULL, is_refundable BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_fee_head_code_college UNIQUE (college_id, code));
CREATE INDEX ix_fee_heads_college_type ON fee_heads (college_id, head_type);
CREATE TABLE fee_templates (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(160) NOT NULL, version INTEGER NOT NULL DEFAULT 1, program VARCHAR(120), class_name VARCHAR(80), section VARCHAR(80), frequency VARCHAR(32) NOT NULL, effective_from DATE NOT NULL, effective_to DATE, is_active BOOLEAN NOT NULL DEFAULT TRUE, CONSTRAINT uq_fee_template_version UNIQUE (college_id, code, version));
CREATE INDEX ix_fee_templates_scope ON fee_templates (college_id, program, class_name, section);
CREATE TABLE fee_template_lines (id VARCHAR(36) PRIMARY KEY, template_id VARCHAR(36) NOT NULL REFERENCES fee_templates(id) ON DELETE CASCADE, fee_head_id VARCHAR(36) NOT NULL REFERENCES fee_heads(id), amount NUMERIC(12,2) NOT NULL CHECK (amount > 0), CONSTRAINT uq_template_fee_head UNIQUE (template_id, fee_head_id));
CREATE TABLE fee_challans (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, challan_number VARCHAR(60) NOT NULL, student_id VARCHAR(36) NOT NULL, billing_period VARCHAR(30) NOT NULL, issue_date DATE NOT NULL, due_date DATE NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'ISSUED', subtotal NUMERIC(12,2) NOT NULL DEFAULT 0, discount_total NUMERIC(12,2) NOT NULL DEFAULT 0, late_fine NUMERIC(12,2) NOT NULL DEFAULT 0, carry_forward NUMERIC(12,2) NOT NULL DEFAULT 0, paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0, total_amount NUMERIC(12,2) NOT NULL DEFAULT 0, balance_amount NUMERIC(12,2) NOT NULL DEFAULT 0, notes TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_challan_number_college UNIQUE (college_id, challan_number));
CREATE INDEX ix_challans_student_status_due ON fee_challans (college_id, student_id, status, due_date);
CREATE TABLE fee_challan_lines (id VARCHAR(36) PRIMARY KEY, challan_id VARCHAR(36) NOT NULL REFERENCES fee_challans(id) ON DELETE CASCADE, fee_head_id VARCHAR(36) NOT NULL REFERENCES fee_heads(id), description VARCHAR(200) NOT NULL, amount NUMERIC(12,2) NOT NULL CHECK (amount > 0));
CREATE TABLE scholarships (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, student_id VARCHAR(36) NOT NULL, scholarship_type VARCHAR(32) NOT NULL, title VARCHAR(160) NOT NULL, percentage NUMERIC(5,2), amount NUMERIC(12,2), effective_from DATE NOT NULL, effective_to DATE, renewal_rule VARCHAR(200), status VARCHAR(32) NOT NULL DEFAULT 'PENDING', approved_by VARCHAR(64));
CREATE INDEX ix_scholarships_college_student_status ON scholarships (college_id, student_id, status);
CREATE TABLE installment_plans (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, challan_id VARCHAR(36) NOT NULL REFERENCES fee_challans(id) ON DELETE CASCADE, student_id VARCHAR(36) NOT NULL, number_of_installments INTEGER NOT NULL CHECK (number_of_installments BETWEEN 2 AND 24), penalty_amount NUMERIC(12,2) NOT NULL DEFAULT 0, status VARCHAR(32) NOT NULL DEFAULT 'PENDING', approved_by VARCHAR(64));
CREATE TABLE fee_payments (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, challan_id VARCHAR(36) NOT NULL REFERENCES fee_challans(id) ON DELETE CASCADE, amount NUMERIC(12,2) NOT NULL CHECK (amount > 0), method VARCHAR(32) NOT NULL, reference_number VARCHAR(120) NOT NULL, paid_on DATE NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'RECONCILED', received_by VARCHAR(64) NOT NULL);
CREATE INDEX ix_payments_college_reference ON fee_payments (college_id, reference_number);
CREATE INDEX ix_payments_college_method_status ON fee_payments (college_id, method, status);
CREATE TABLE fee_refunds (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, payment_id VARCHAR(36) NOT NULL REFERENCES fee_payments(id), amount NUMERIC(12,2) NOT NULL CHECK (amount > 0), reason TEXT NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'REQUESTED', requested_by VARCHAR(64) NOT NULL, approved_by VARCHAR(64), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
