-- Marks Entry schema migration for PostgreSQL.
CREATE TABLE IF NOT EXISTS marks_entry_batches (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, exam_id varchar(36) NOT NULL REFERENCES exams(id) ON DELETE CASCADE, section_id varchar(36) NOT NULL REFERENCES sections(id) ON DELETE CASCADE, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, component_id varchar(36) NOT NULL REFERENCES assessment_components(id) ON DELETE RESTRICT, status varchar(20) NOT NULL DEFAULT 'draft', created_by varchar(64) NOT NULL, submitted_by varchar(64), submitted_at timestamptz, locked_by varchar(64), locked_at timestamptz, unlocked_by varchar(64), unlocked_at timestamptz, unlock_reason text, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT uq_marks_batch_scope UNIQUE (college_id, exam_id, subject_id, component_id, section_id));
CREATE TABLE IF NOT EXISTS marks_entries (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, batch_id varchar(36) NOT NULL REFERENCES marks_entry_batches(id) ON DELETE CASCADE, exam_id varchar(36) NOT NULL REFERENCES exams(id) ON DELETE CASCADE, section_id varchar(36) NOT NULL REFERENCES sections(id) ON DELETE CASCADE, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, component_id varchar(36) NOT NULL REFERENCES assessment_components(id) ON DELETE RESTRICT, student_id varchar(36) NOT NULL REFERENCES students(id) ON DELETE CASCADE, marks_obtained numeric(7,2) NOT NULL, moderation_marks numeric(7,2) NOT NULL DEFAULT 0, recheck_notes text, remarks text, entered_by varchar(64) NOT NULL, updated_by varchar(64), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT uq_marks_entry_batch_student UNIQUE (batch_id, student_id), CONSTRAINT uq_marks_entry_exam_subject_component_student UNIQUE (college_id, exam_id, subject_id, component_id, student_id), CONSTRAINT ck_marks_obtained_non_negative CHECK (marks_obtained >= 0), CONSTRAINT ck_marks_moderation_range CHECK (moderation_marks >= -1000 AND moderation_marks <= 1000));
CREATE TABLE IF NOT EXISTS marks_audit_trails (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, batch_id varchar(36) NOT NULL REFERENCES marks_entry_batches(id) ON DELETE CASCADE, entry_id varchar(36) REFERENCES marks_entries(id) ON DELETE SET NULL, action varchar(20) NOT NULL, actor_id varchar(64) NOT NULL, old_value text, new_value text, reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_marks_batches_college_exam_status ON marks_entry_batches(college_id, exam_id, status);
CREATE INDEX IF NOT EXISTS ix_marks_batches_college_section_subject ON marks_entry_batches(college_id, section_id, subject_id);
CREATE INDEX IF NOT EXISTS ix_marks_entries_college_student_exam ON marks_entries(college_id, student_id, exam_id);
CREATE INDEX IF NOT EXISTS ix_marks_entries_college_exam_subject ON marks_entries(college_id, exam_id, subject_id);
CREATE INDEX IF NOT EXISTS ix_marks_audit_college_batch_created ON marks_audit_trails(college_id, batch_id, created_at);
CREATE INDEX IF NOT EXISTS ix_marks_audit_college_entry_created ON marks_audit_trails(college_id, entry_id, created_at);
