-- Timetable Management schema migration for PostgreSQL.
CREATE TABLE IF NOT EXISTS classrooms (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, campus_id varchar(36) REFERENCES campuses(id) ON DELETE SET NULL, name varchar(160) NOT NULL, code varchar(40) NOT NULL, room_type varchar(20) NOT NULL, capacity integer NOT NULL, is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_classroom_code_per_college UNIQUE (college_id, code), CONSTRAINT ck_classroom_capacity_positive CHECK (capacity > 0));
CREATE TABLE IF NOT EXISTS time_slots (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, name varchar(80) NOT NULL, start_time time NOT NULL, end_time time NOT NULL, sort_order integer NOT NULL DEFAULT 0, is_break boolean NOT NULL DEFAULT false, CONSTRAINT uq_time_slot_name_per_college UNIQUE (college_id, name), CONSTRAINT ck_time_slot_range CHECK (start_time < end_time));
CREATE TABLE IF NOT EXISTS working_days (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, session_id varchar(36) NOT NULL REFERENCES academic_sessions(id) ON DELETE CASCADE, weekday integer NOT NULL, is_working boolean NOT NULL DEFAULT true, CONSTRAINT uq_working_day_session_weekday UNIQUE (college_id, session_id, weekday));
CREATE TABLE IF NOT EXISTS calendar_events (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, session_id varchar(36) NOT NULL REFERENCES academic_sessions(id) ON DELETE CASCADE, title varchar(180) NOT NULL, start_date date NOT NULL, end_date date NOT NULL, is_holiday boolean NOT NULL DEFAULT false, description text, CONSTRAINT ck_calendar_event_date_range CHECK (start_date <= end_date));
CREATE TABLE IF NOT EXISTS timetable_versions (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, session_id varchar(36) NOT NULL REFERENCES academic_sessions(id) ON DELETE RESTRICT, section_id varchar(36) NOT NULL REFERENCES sections(id) ON DELETE CASCADE, version_number integer NOT NULL, status varchar(20) NOT NULL, effective_from date NOT NULL, effective_to date NOT NULL, created_by varchar(64) NOT NULL, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT uq_timetable_version_section_number UNIQUE (college_id, section_id, version_number), CONSTRAINT ck_timetable_effective_range CHECK (effective_from <= effective_to));
CREATE TABLE IF NOT EXISTS timetable_entries (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, version_id varchar(36) NOT NULL REFERENCES timetable_versions(id) ON DELETE CASCADE, session_id varchar(36) NOT NULL REFERENCES academic_sessions(id) ON DELETE RESTRICT, section_id varchar(36) NOT NULL REFERENCES sections(id) ON DELETE CASCADE, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, teacher_id varchar(64) NOT NULL, teacher_name varchar(160) NOT NULL, classroom_id varchar(36) NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT, time_slot_id varchar(36) NOT NULL REFERENCES time_slots(id) ON DELETE RESTRICT, weekday integer NOT NULL, entry_type varchar(20) NOT NULL, notes text, CONSTRAINT uq_entry_version_day_slot UNIQUE (version_id, weekday, time_slot_id));
CREATE INDEX IF NOT EXISTS ix_classrooms_college_type ON classrooms(college_id, room_type);
CREATE INDEX IF NOT EXISTS ix_time_slots_college_order ON time_slots(college_id, sort_order);
CREATE INDEX IF NOT EXISTS ix_calendar_events_college_session_dates ON calendar_events(college_id, session_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS ix_timetable_versions_college_section_status ON timetable_versions(college_id, section_id, status);
CREATE INDEX IF NOT EXISTS ix_timetable_entries_teacher_day_slot ON timetable_entries(college_id, teacher_id, weekday, time_slot_id);
CREATE INDEX IF NOT EXISTS ix_timetable_entries_room_day_slot ON timetable_entries(college_id, classroom_id, weekday, time_slot_id);
CREATE INDEX IF NOT EXISTS ix_timetable_entries_section_day_slot ON timetable_entries(college_id, section_id, weekday, time_slot_id);
