-- Academic Management schema migration for PostgreSQL.
-- Mirrors backend/app/modules/academic/models.py with tenant-aware constraints and indexes.
CREATE TABLE IF NOT EXISTS institutions (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, name varchar(180) NOT NULL, code varchar(40) NOT NULL, address text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT uq_institution_code_per_college UNIQUE (college_id, code));
CREATE TABLE IF NOT EXISTS campuses (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, institution_id varchar(36) NOT NULL REFERENCES institutions(id) ON DELETE CASCADE, name varchar(180) NOT NULL, code varchar(40) NOT NULL, address text, is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_campus_code_per_institution UNIQUE (institution_id, code));
CREATE TABLE IF NOT EXISTS departments (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, institution_id varchar(36) NOT NULL REFERENCES institutions(id) ON DELETE CASCADE, campus_id varchar(36) REFERENCES campuses(id) ON DELETE SET NULL, name varchar(180) NOT NULL, code varchar(40) NOT NULL, is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_department_code_per_college UNIQUE (college_id, code));
CREATE TABLE IF NOT EXISTS academic_sessions (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, name varchar(80) NOT NULL, start_date date NOT NULL, end_date date NOT NULL, status varchar(20) NOT NULL, is_locked boolean NOT NULL DEFAULT false, CONSTRAINT uq_academic_session_name_per_college UNIQUE (college_id, name), CONSTRAINT ck_academic_session_date_range CHECK (start_date < end_date));
CREATE TABLE IF NOT EXISTS programs (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, department_id varchar(36) NOT NULL REFERENCES departments(id) ON DELETE RESTRICT, name varchar(180) NOT NULL, code varchar(40) NOT NULL, duration_years integer NOT NULL, is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_program_code_per_college UNIQUE (college_id, code));
CREATE TABLE IF NOT EXISTS academic_classes (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, program_id varchar(36) NOT NULL REFERENCES programs(id) ON DELETE RESTRICT, session_id varchar(36) NOT NULL REFERENCES academic_sessions(id) ON DELETE RESTRICT, name varchar(100) NOT NULL, display_order integer NOT NULL DEFAULT 0, is_archived boolean NOT NULL DEFAULT false, CONSTRAINT uq_class_name_program_session UNIQUE (college_id, program_id, session_id, name));
CREATE TABLE IF NOT EXISTS sections (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, class_id varchar(36) NOT NULL REFERENCES academic_classes(id) ON DELETE CASCADE, name varchar(80) NOT NULL, capacity integer NOT NULL, enrolled_count integer NOT NULL DEFAULT 0, room varchar(80), is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_section_name_per_class UNIQUE (class_id, name), CONSTRAINT ck_section_capacity_positive CHECK (capacity > 0), CONSTRAINT ck_section_enrolled_non_negative CHECK (enrolled_count >= 0), CONSTRAINT ck_section_capacity_not_exceeded CHECK (enrolled_count <= capacity));
CREATE TABLE IF NOT EXISTS subjects (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, department_id varchar(36) REFERENCES departments(id) ON DELETE SET NULL, code varchar(40) NOT NULL, name varchar(180) NOT NULL, credit_hours integer NOT NULL DEFAULT 1, weekly_periods integer NOT NULL DEFAULT 1, is_elective boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, CONSTRAINT uq_subject_code_per_college UNIQUE (college_id, code));
CREATE TABLE IF NOT EXISTS subject_prerequisites (id varchar(36) PRIMARY KEY, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE CASCADE, prerequisite_subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, CONSTRAINT uq_subject_prerequisite UNIQUE (subject_id, prerequisite_subject_id));
CREATE TABLE IF NOT EXISTS subject_groups (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, name varchar(160) NOT NULL, description text, CONSTRAINT uq_subject_group_name_per_college UNIQUE (college_id, name));
CREATE TABLE IF NOT EXISTS elective_groups (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, class_id varchar(36) NOT NULL REFERENCES academic_classes(id) ON DELETE CASCADE, name varchar(160) NOT NULL, min_subjects integer NOT NULL DEFAULT 1, max_subjects integer NOT NULL DEFAULT 1, CONSTRAINT uq_elective_group_name_per_class UNIQUE (class_id, name));
CREATE TABLE IF NOT EXISTS subject_allocations (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, class_id varchar(36) NOT NULL REFERENCES academic_classes(id) ON DELETE CASCADE, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, subject_group_id varchar(36) REFERENCES subject_groups(id) ON DELETE SET NULL, elective_group_id varchar(36) REFERENCES elective_groups(id) ON DELETE SET NULL, is_mandatory boolean NOT NULL DEFAULT true, weekly_periods integer NOT NULL, CONSTRAINT uq_subject_allocation_class_subject UNIQUE (class_id, subject_id));
CREATE TABLE IF NOT EXISTS teacher_assignments (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, teacher_id varchar(64) NOT NULL, teacher_name varchar(160) NOT NULL, section_id varchar(36) NOT NULL REFERENCES sections(id) ON DELETE CASCADE, subject_id varchar(36) NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT, weekly_periods integer NOT NULL, max_weekly_periods integer NOT NULL DEFAULT 30, status varchar(20) NOT NULL DEFAULT 'ACTIVE', CONSTRAINT uq_teacher_assignment_section_subject_teacher UNIQUE (section_id, subject_id, teacher_id));
CREATE TABLE IF NOT EXISTS promotion_rules (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, from_class_id varchar(36) NOT NULL REFERENCES academic_classes(id) ON DELETE CASCADE, to_class_id varchar(36) NOT NULL REFERENCES academic_classes(id) ON DELETE CASCADE, minimum_attendance_percentage integer NOT NULL DEFAULT 75, minimum_passing_percentage integer NOT NULL DEFAULT 40, require_all_mandatory_subjects boolean NOT NULL DEFAULT true, CONSTRAINT uq_promotion_rule_from_to UNIQUE (from_class_id, to_class_id));
CREATE TABLE IF NOT EXISTS academic_archives (id varchar(36) PRIMARY KEY, college_id varchar(64) NOT NULL, entity_type varchar(80) NOT NULL, entity_id varchar(36) NOT NULL, session_id varchar(36), snapshot text NOT NULL, archived_by varchar(64) NOT NULL, archived_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_academic_sessions_college_status ON academic_sessions(college_id, status);
CREATE INDEX IF NOT EXISTS ix_classes_college_program_session ON academic_classes(college_id, program_id, session_id);
CREATE INDEX IF NOT EXISTS ix_sections_college_class ON sections(college_id, class_id);
CREATE INDEX IF NOT EXISTS ix_teacher_assignments_teacher_status ON teacher_assignments(college_id, teacher_id, status);
