CREATE TABLE certificate_templates (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, certificate_type VARCHAR(32) NOT NULL, version INTEGER NOT NULL DEFAULT 1, body_template TEXT NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_certificate_template_code_version UNIQUE (college_id, code, version));
CREATE INDEX ix_certificate_templates_college_type ON certificate_templates (college_id, certificate_type, is_active);
CREATE TABLE certificate_requests (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, template_id VARCHAR(36) REFERENCES certificate_templates(id) ON DELETE SET NULL, certificate_type VARCHAR(32) NOT NULL, student_id VARCHAR(36), employee_id VARCHAR(64), purpose VARCHAR(240) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'PENDING_APPROVAL', requested_by VARCHAR(64) NOT NULL, approved_by VARCHAR(64), approved_at TIMESTAMP, rejection_reason TEXT, issued_by VARCHAR(64), issued_at TIMESTAMP, verification_code VARCHAR(96) NOT NULL UNIQUE, rendered_html TEXT, qr_payload TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_certificate_requests_college_student_status ON certificate_requests (college_id, student_id, status);
CREATE INDEX ix_certificate_requests_college_type_status ON certificate_requests (college_id, certificate_type, status);
CREATE INDEX ix_certificate_requests_verification_code ON certificate_requests (verification_code);
CREATE TABLE document_repository_items (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, owner_type VARCHAR(40) NOT NULL, owner_id VARCHAR(64) NOT NULL, document_type VARCHAR(32) NOT NULL, title VARCHAR(180) NOT NULL, file_path VARCHAR(500) NOT NULL, mime_type VARCHAR(120) NOT NULL, checksum_sha256 VARCHAR(64) NOT NULL, approval_status VARCHAR(32) NOT NULL DEFAULT 'PENDING', uploaded_by VARCHAR(64) NOT NULL, approved_by VARCHAR(64), approved_at TIMESTAMP, rejection_reason TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_documents_college_owner_status ON document_repository_items (college_id, owner_type, owner_id, approval_status);
CREATE INDEX ix_documents_college_type ON document_repository_items (college_id, document_type);
