CREATE TABLE notification_templates (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, event_type VARCHAR(40) NOT NULL, channel VARCHAR(30) NOT NULL, subject_template VARCHAR(200), body_template TEXT NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_notification_template_code_channel UNIQUE (college_id, code, channel));
CREATE INDEX ix_notification_templates_college_event ON notification_templates (college_id, event_type, is_active);
CREATE TABLE notifications (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, template_id VARCHAR(36) REFERENCES notification_templates(id) ON DELETE SET NULL, recipient_type VARCHAR(30) NOT NULL, recipient_id VARCHAR(64) NOT NULL, recipient_address VARCHAR(255), channel VARCHAR(30) NOT NULL, event_type VARCHAR(40) NOT NULL, priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL', subject VARCHAR(200), body TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'QUEUED', scheduled_for TIMESTAMP, sent_at TIMESTAMP, retry_count INTEGER NOT NULL DEFAULT 0, max_retries INTEGER NOT NULL DEFAULT 3, last_error TEXT, created_by VARCHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_notifications_college_recipient_status ON notifications (college_id, recipient_type, recipient_id, status);
CREATE INDEX ix_notifications_college_scheduled ON notifications (college_id, status, scheduled_for);
CREATE TABLE notification_delivery_attempts (id VARCHAR(36) PRIMARY KEY, notification_id VARCHAR(36) NOT NULL REFERENCES notifications(id) ON DELETE CASCADE, provider VARCHAR(80) NOT NULL, status VARCHAR(20) NOT NULL, response_code VARCHAR(80), response_message TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_notification_attempts_notification_created ON notification_delivery_attempts (notification_id, created_at);
CREATE TABLE announcements (id VARCHAR(36) PRIMARY KEY, college_id VARCHAR(64) NOT NULL, title VARCHAR(180) NOT NULL, message TEXT NOT NULL, audience VARCHAR(30) NOT NULL, published_at TIMESTAMP, expires_at TIMESTAMP, created_by VARCHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_announcements_college_audience ON announcements (college_id, audience, published_at);
