import { useEffect, useState } from 'react';
import { meritListsApi } from '../../services/meritLists';
export function MeritListsPage() {
  const [items,setItems]=useState<any[]>([]); const [examId,setExamId]=useState(''); const [scope,setScope]=useState<'institution'|'program'|'class'|'section'|'session'>('institution'); const [scopeId,setScopeId]=useState(''); const [basis,setBasis]=useState<'percentage'|'gpa'>('percentage'); const [title,setTitle]=useState('Merit List'); const [error,setError]=useState<string|null>(null);
  const load=async()=>{const data=await meritListsApi.list(examId?`?exam_id=${encodeURIComponent(examId)}`:''); setItems(data.items??[])};
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  const generate=async()=>{setError(null); await meritListsApi.generate({exam_id:examId,scope_type:scope,scope_id:scopeId||undefined,basis,title,tie_breakers:['admission_number']}); await load();};
  return <section style={{border:'1px solid #d7dce2',borderRadius:12,padding:'1rem',marginBlock:'1rem'}}><h2>Merit Lists</h2><p>Generate institution, program, class, section, or session merit lists by percentage or GPA with publication workflow.</p><div style={{display:'flex',gap:'.75rem',flexWrap:'wrap'}}><input aria-label="Exam ID" placeholder="Exam ID" value={examId} onChange={e=>setExamId(e.target.value)}/><input aria-label="Title" value={title} onChange={e=>setTitle(e.target.value)}/><select aria-label="Scope" value={scope} onChange={e=>setScope(e.target.value as any)}><option value="institution">Institution</option><option value="program">Program</option><option value="class">Class</option><option value="section">Section</option><option value="session">Session</option></select><input aria-label="Scope ID" placeholder="Scope value" value={scopeId} onChange={e=>setScopeId(e.target.value)}/><select aria-label="Basis" value={basis} onChange={e=>setBasis(e.target.value as any)}><option value="percentage">Percentage</option><option value="gpa">GPA</option></select><button disabled={!examId} onClick={generate}>Generate</button><button onClick={load}>Search</button></div>{error&&<p role="alert" style={{color:'#b42318'}}>{error}</p>}<div style={{overflowX:'auto',marginTop:'1rem'}}><table><thead><tr><th>Title</th><th>Scope</th><th>Basis</th><th>Status</th><th>Top entries</th><th>Actions</th></tr></thead><tbody>{items.map(m=><tr key={m.id}><td>{m.title}</td><td>{m.scope_type}:{m.scope_id||'all'}</td><td>{m.basis}</td><td>{m.status}</td><td>{(m.items??[]).slice(0,3).map((i:any)=>`#${i.rank} ${i.student_id} (${i.score})`).join(', ')}</td><td><button disabled={m.status!=='draft'} onClick={async()=>{await meritListsApi.publish(m.id); await load();}}>Publish</button><button disabled={m.status!=='published'} onClick={async()=>{await meritListsApi.lock(m.id); await load();}}>Lock</button></td></tr>)}</tbody></table></div></section>;
}
